version: 2
jobs:
  test:
    working_directory: /go/src/github.com/gojekfarm/iap_auth
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - restore_cache:
          keys:
          - vendor-pkg-{{ checksum "go.sum" }}
          - vendor-pkg-
      - run:
          name: Install Dependencies
          command: |
            make setup
      - save_cache:
          paths:
            - ./vendor
            - "/go/pkg"
          key: vendor-pkg-{{ checksum "go.sum" }}
      - run:
          name: Run tests
          command: |
            env GO111MODULE=on go mod verify
            env GO111MODULE=on CGO_ENABLED=0 make
  release:
    working_directory: /go/src/github.com/gojekfarm/iap_auth
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - restore_cache:
          keys:
          - vendor-pkg-{{ checksum "go.sum" }}
          - vendor-pkg-
      - run:
          name: Install Dependencies
          command: |
            make setup
      - save_cache:
          paths:
            - ./vendor
            - "/go/pkg"
          key: vendor-pkg-{{ checksum "go.sum" }}
      - run:
          name: Release go binary
          command: |
            env GO111MODULE=on CGO_ENABLED=0 make
            curl -sL https://git.io/goreleaser | bash
      - run:
          name: Docker Build
          command: |
            TAG=0.1.0-$CIRCLE_SHA1
            docker build -t gojektech/iap-auth:$TAG .
      - run:
          name: Docker Publish
          command: |
            TAG=0.1.0-$CIRCLE_SHA1
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push gojektech/iap-auth:$TAG
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - release:
          requires:
            - test

